site_name: 白鲨想睡觉
site_url: https://abab996.github.io/
site_author: 白鲨
theme:
 name: material             # 推荐使用 material 主题
 palette:
   primary: indigo          # 主色调
   accent: blue             # 强调色
#repo_url: https://github.com/abab996/abab996.github.io
nav:
  - Home: index.md
  - 资源: things.md
  - 收藏:
      - 软件: app.md
      - 网页: web.md
      - 游戏: game.md
  - 关于: about.md